movieReviews/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movies.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movies/urls.py
from django.contrib import admin
from django.urls import path,reverse_lazy,re_path
from django.conf.urls import include, url
from . import views
from accounts.views import (login_view, register_view, logout_view,add_review)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'movies'

urlpatterns = [
                  path('', views.post_list, name='home'),
                  path('loginn', login_view, name='login'),
                  path('logout', logout_view, name='logout'),
                  path('register', register_view, name='register'),
                  path('recommendation', views.recommendation, name='recommendation'),
                  path('detail/<int:id>', views.detail, name='detail'),
                  path('addreview/<int:id>',add_review,name="add_review"),
                  path('search',views.search,name="search"),
                  path('editreview/<int:review_id>',views.edit_review,name="edit_review"),
                  path('deletereview/<int:review_id>',views.delete_review,name="delete_review"),
                  re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(
                      email_template_name='registration/password_reset_email.html',
                      success_url=reverse_lazy('movies:password_reset_done'),
                      template_name= "registration/password_reset_form.html"),
                            name='password_reset'),
                  re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(
                      template_name= "registration/password_reset_done.html"),
                            name='password_reset_done'),
                  re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,23})/$',
                            auth_views.PasswordResetConfirmView.as_view(
                            template_name= "registration/password_reset_confirm.html",
                            success_url=reverse_lazy('movies:password_reset_complete')
                            ),
                            name='password_reset_confirm'),
                  re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(
                             template_name= "registration/password_reset_complete.html"
                              ),
                            name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movies/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.

class Movies(models.Model):
    title = models.CharField(max_length=30)
    genres = models.CharField(max_length=50)
    photo=models.ImageField(upload_to='%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'

    def __str__(self):
        return self.title
    
    def __unicode__(self):
        return self.title

class Ratings(models.Model):
    userid = models.ForeignKey(User, on_delete=models.CASCADE)
    movieid = models.ForeignKey(Movies, on_delete=models.CASCADE)
    rating = models.FloatField()
    comment=models.TextField(max_length=1000,blank=True,null=True)
    class Meta:
        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'
    
    def __str__(self):
        return self.userId.username

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Movie Recommendation</title>
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
        integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <!-- Material Design Bootstrap -->
    <link href='{% static "css/mdb.min.css" %}' rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <style>
        
        .pagination {
            margin: 20px;
            display: inherit;
        }
        .pagination .step-links a{
            background: linear-gradient(45deg, #7d7194, #464c71);
            color: white;
            padding: 4px 8px;
            border-radius: 50%;
            text-align: center;
        }

        .pagination .step-links .current{
            color: white;
            background: linear-gradient(45deg, #7d7194, #464c71);
            padding: 4px 8px;
            margin: 3px;
            border-radius: 8px;
            text-align: center;
        }

        .pagination .step-links a i{
            color: white;
        }
        .social-media {
            margin-top:10px; 
        }
        .social-media a{
            color: white;
            font-size: 1rem;
            margin: 2px 4px;
            text-decoration: none;
        }
    </style>
    <style type="text/css">
    .hero {
    /* Sizing */
    width: 100%;
    height: 60vh;
    
    /* Flexbox stuff */
    display: flex;
    justify-content: center;
    align-items: center;
    
    /* Text styles */
    text-align: center;
    color: #fff; /* ADD THIS LINE */
    
    /* Background styles */
    background-image: url('https://images.unsplash.com/photo-1517370725918-a2e550ba7394?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80');
    background-size: cover;
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
}

.hero h1 {
    /* Text styles */
    font-size: 5em;
    
    /* Margins */
    margin-top: 70px;
    margin-bottom: 0.5em;
}

.preview-img img{
    width: 100%;
    object-fit: cover;
    object-position: center;
    max-height: 35vh;
}

</style>
</head>

<body class="fixed-sn deep-purple-skin">

    <!--Double navigation-->
    <header>
       
        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-toggleable-md navbar-expand-lg young-passion-gradient scrolling-navbar double-nav" style="background:linear-gradient(45deg, #7d7194, #464c71);">
            
            <!-- Breadcrumb-->
            <div class="breadcrumb-dn mr-fix">
                 <a href="{% url 'movies:home' %}"> 
                <img style="max-width: 30px;max-height: 30px;" src="{% static 'img/logo.png' %}"></a>
            </div>

                <div class="breadcrumb-dn mr-fix">
                <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'movies:home' %}">
                <input class="form-control mr-sm-2" size="60" style="margin-left:400px" type="search" placeholder="Search" aria-label="Search" name="title">
                    <i class="fas fa-search"style="color: white"></i>
                </form>
                </div>

            <ul class="nav navbar-nav nav-flex-icons ml-auto" style="color:white ">

                <li class="nav-item">
                    <a href="{% url 'movies:home' %}" class="nav-link"style="color: white"><i class="fas fa-home"></i> <span
                            class="clearfix d-none d-sm-inline-block"style="color: white">Home</span></a>


                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'movies:recommendation' %}" class="nav-link"style="color: white"><i class="fas fa-fire"></i> <span
                            class="clearfix d-none d-sm-inline-block"style="color: white">Recommendations</span></a>
                </li>

                <!-- Dropdown -->
                <li class="nav-item dropdown" style="cursor:pointer;">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i> <span
                            class="clearfix d-none d-sm-inline-block"style="color: white;">{{user_name}}</span></a>
                    <section class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'movies:logout' %}">Logout</a>
                    </section>
                 {% else %}
                     <li class="nav-item">
                    <a href="{% url 'movies:login' %}" class="nav-link"style="color: white"><i class="fas fa-user"></i> <span
                            class="clearfix d-none d-sm-inline-block"style="color: white">Login</span></a>
                </li>

                {% endif %}
               
            </ul>
        </nav>
        <!-- /.Navbar -->
    </header>
    <!--/.Double navigation-->
    <!--Main layout-->
    <div style="margin-top: 50px;">
        {% block body %} {% endblock %}

    </div>
    <footer>
        <div class="footer" style="background:linear-gradient(45deg, #7d7194, #464c71); width: 100;">
            <div class="d-flex flex-column justify-content-between align-items-center">
                <div class="social-media" style="font-size: 1rem; color: white;">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-instagram"></a>
                </div>
                <div style="font-size: 1rem; color: white"><p>All Rights Reserved &copy;</p></div>
            </div>
        </div>
    </footer>
   
    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <!-- Tooltips -->
    <!-- <script type="text/javascript" src="https://mdbootstrap.com/previews/docs/latest/js/popper.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>
    <!-- MDB core JavaScript -->
    <!-- <script type="text/javascript" src="https://mdbootstrap.com/previews/docs/latest/js/mdb.min.js"></script> -->
    <script type="text/javascript" src='{% static "js/mdb.min.js" %}'></script>

    <script type="text/javascript">
        $(".button-collapse").sideNav();

        new WOW().init();
    </script>

</body>

</html>

templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block body %}
<style type="text/css">
    .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}
</style>
<div class="container" style="margin-top: 130px">
<div style="margin-top:-20px;"
            class='card text-black blue-gradient mb-3' style="max-width: 20rem;">
            <div class="card-header "style="background: linear-gradient(45deg, #7d7194, #464c71); color:white;padding-top:10px;margin-bottom:-7px";padding-top:3px><h5 >{{detail.title}}</h5></div>
            <div class="card-body"style="background: #f5eeee">
                <div class="row">
                <div class="column" style=" float: left;padding-left: 10px;
  width: 50%;">

                <h5 class="card-text text-black">Genre: {{detail.genres}}</h5>

                <h5 class="card-text text-black">Rating: {{rating.rating|floatformat:2}}</h5>
                <br>
                   <h5 class="card-title" >Synopsis</h5>
 <p >{{detail.description}}</p>
            </div>
            <div class="column" style=" float: right;
  width: 50%;">
                <!-- <img src="/media/{{detail.photo}}" class="center"> -->
                <video style="outline: none;" width="530" height="440" controls autoplay>
                  <source class="center" src="{% static 'video/movie.mp4' %}" type="video/mp4"> </source>
                  {% static 'img/logo.png' %}
                </video>
            </div>
        </div>
            </div>
        </div>
        {% if condition == "false" %}
        <div class="card">
            <div class="card-body"style="background: #f5eeee"   >
                <h3 class="text-center">Add Review</h3>
                <form action="{% url 'movies:add_review' detail.id %}" method="POST">
                    {% csrf_token %}
                    <label >Review</label>
                    <textarea name="comment" cols="30" rows="5" class="form-control"></textarea>

                    <label for="rating">Rating:</label>


                    <input style="margin-top:4px;" type="range" name="rating" id="rating" value="0" min="1" max="5" step="0.5" oninput="OutputId.value = rating.value"
                    >
                   <output name="output" id="OutputId">0</output>




                    <br>
                    <input type="submit" class="btn btn-primary" value="Add Review">

                </form>
            </div>
        </div>
        {% else %}
        <div class="card">
            <div class="card-body"style="background: #f5eeee">
                <h3 class="text-center">You have already reviewed this movie.</h3>
            </div>
        </div>
        {% endif %}
        <br>
        {% if count == 0 %}
         <div class="card box">
            <div class="card-body" style="background: #f5eeee">
                <h3 class="text-center">No Reviews</h3>
            </div>
        </div>
        {% else %}
        <div class="card box">
            <div class="card-body" style="background: #f5eeee">
                <h3 class="text-center">Reviews</h3>
                <ul id="myList" style="list-style:none;padding-left: 0px;" >
                {% for review in reviews %}
                    <li class="card">
                        <div class="card-body" >
                            <div class="row">

                                <div class="col-md-3">

                                    <h5 class="text-left" style="text-transform: capitalize;">{{review.userid.username}}</h5>
                                    <h5>{{review.rating}}</h5>
                                    {% if current_user == review.userid.id %}
                                    <a href="{% url 'movies:edit_review' review.id %}">Edit</a>
                                    <a href="{% url 'movies:delete_review' review.id %}" 
                                    onclick="return confirm('Are you sure you want to delete it?');">Delete</a>
                                    {% endif %}

                                </div>
                                <div class="col-md-9">  
                                  <p>{{ review.comment }}  </p>

                            </div>

                            </div>

                        </div>

                    </li>
                 <li><br></li>
                {% endfor %}
                </ul>
                {% if count > 3 %}
                <center><input id="loadMore" type="submit" class="btn btn-primary" value="Load More"></center>
                {% endif %}
            </div>
        </div>
{% endif %}
</div>
<style type="text/css">
    #myList li{ display:none;

}
#loadMore {
  
    cursor:pointer;
}
#loadMore:hover {
    color:black;
}
#showLess {
    color:red;
    cursor:pointer;
}
#showLess:hover {
    color:black;
}
</style>
<script type="text/javascript">

    $(function () {
    $("li").slice(0,8).show();
    $("#loadMore").on('click', function (e) {
        e.preventDefault();
        $("li:hidden").slice(0,8).slideDown();
        if ($("li:hidden").length == 0) {
            $("#load").fadeOut('slow');
        }
        $('html,body').animate({
            scrollTop: $(this).offset().top
        }, 1500);
    });

});
</script>

{% endblock body %}

templates/edit_review.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block body %}
<style type="text/css">

	#id_comment{
	
		width:100%;
		height: 200px;

}

#id_rating{
	width: 100%;
}
</style>
<div class="container" style="margin-top: 130px;">
<div class="card">
	<div class="card-body "style="background: #f5eeee">
		<h3 class="text-center">Edit Review</h3>
		<form action="" method="POST">
			{% csrf_token %}
			{{form | crispy}}
			{% if error %}
				<strong style="color: red">{{ error }}</strong>
			{% endif %}
			<br>
			<input type="submit" value="Save Changes" class="btn btn-primary">
		</form>
	</div>
</div>

</div>
{% endblock body %}

templates/form.html
{% extends "base.html" %}

{% block body %}
<div class="container" style="margin: 130px">
<center>
    <div class="col-md-5">


        <!-- Material form contact -->
        <div class="card">

            <h5 class="card-header info-color white-text text-center py-4">
                <strong>{{title}}</strong>
            </h5>

            <!--Card content-->
            <div class="card-body px-lg-5 pt-0">

                <!-- Form -->
                <form class="text-center" method="POST" style="color: #757575;">
                    {% csrf_token %}
                    <div class="md-form mt-3">
                        {{ form.as_p }}
                    </div>

                    <!-- Register -->
                    <p>Not a member?
                        <a href="{% url 'movies:register' %}">Register</a>
                    </p>

                    <a href="{% url 'movies:password_reset' %}"><p>Forget Password?</p></a>
                    <!-- Send button -->
                    <button class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4 waves-effect"
                        type="submit">Login</button>

                </form>
                <!-- Form -->

            </div>

        </div>
        <!-- Material form contact -->
    </div>


</center>
</div>
{% endblock body %}

templates/home.html
{% extends 'base.html' %}
{% block home %}active{% endblock %}
{% block body %}
{% load static %}

<section class="hero">
    <div class="hero-inner">
        <h1>Watch Unlimited Movies</h1>
        <h2>Find varities of different movies to watch</h2>
    </div>
</section>
<div class="container">
<h2 style="margin-top:40px;" class="text-center">{% if search %}Found {{search_count}} results for "{{ query}}" in movies{% else %}Movies To Watch {% endif %}</h2>
<style type="text/css">
    .chip{
    background: #2196F3;
    padding: 2px 15px;
    margin: 3px;
    border-radius: 30px;
    color: white;
}


</style>
<div class="row">
    {% for a in object_list %}
    <div class="col-md-3">
        <a style="text-decoration: none; color: black;" href="{% url 'movies:detail' id=a.id %}">
        <div style="margin-top:10px;"
            class='card text-black mb-2'>
           <!--  <div class="card-header"  style="background:#3949abd9;color:white"><div class="col-14 text-truncate">{{a.title}}</div></div> -->
            <div class="card-body" >
                <div class="preview-img">
                    {% if a.photo %}
                        <img src="/media/{{a.photo}}" alt="preview-img">
                    {% else %}
                        <img src="http://valmorgan.co.nz/wp-content/uploads/2016/06/default-movie-1-3.jpg" alt="preview-img">
                    {% endif %}
                </div>
                <h4 class="card-text text-black"><div class="col-14 text-truncate" >{{a.title}}</div></h4>
                <p class="card-text text-black" ><div class="col-14 text-truncate">{{a.genres}}</div></p>
               <!--  <a  class="btn btn-sm btn-info" href="{% url 'movies:detail' id=a.id %}">Detail</a> -->
                <br>
               
            </div>
        </div>
    </a>
    </div>
    {% endfor %}
</div>

<div class="pagination pagination-centered m-10">
    <center>
        <span class="step-links">
            {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
            {% endif %}

            <span class="current">
               Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
            </span>

            {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
            {% endif %}
        </span>
    </center>
</div>
</div>
{% endblock %}

templates/recommendation.html
{% extends 'base.html' %}
{% block recommender %}active{% endblock %}
{% block body %}
<section class="hero">
    <div class="hero-inner">
        <h1>Watch Unlimited Movies</h1>
        <h2>Look out for the personalized recommended movies</h2>
    </div>
</section>
<div class="container" style="margin-top:70px; ">
    {% if title%}
<h2 style="margin-top:-40px;" class="text-center">Movies Recommended To You</h2>
    {% else %}
<h2 style="margin-top:-40px;" class="text-center">Popular Movies</h2>
    {% endif %}    
<div class="row">
{%for a in  object_list.itertuples %}
<div class="col-md-3">
     <a style="text-decoration: none; color: black;" href="{% url 'movies:detail' id=a.movieId_id %}">
        <div style="margin-top:10px;"
            class='card text-black mb-3'>
            
           <!--  <div class="card-header" style="background:#3949abd9;color:white""><div class="col-14 text-truncate">{{a.title}}</div></div> -->
            <div class="card-body">
                <div class="preview-img">
                    {% if a.photo %}
                        <img src="/media/{{a.photo}}" alt="preview-img">
                    {% else %}
                        <img src="http://valmorgan.co.nz/wp-content/uploads/2016/06/default-movie-1-3.jpg" alt="preview-img">
                    {% endif %}
                </div>
                <h4 class="card-text text-black"><div class="col-14 text-truncate" >{{a.title}}</div></h4>
                <p class="card-text text-black"><div class="col-14 text-truncate">{{a.genres}}</div></p>
                 <!--  <a class="btn btn-sm btn-info" href="{% url 'movies:detail' id=a.movieId_id %}">Detail</a> -->


        </div>
        </div>
    </a>
    </div>


{% endfor %}
<br>
</div>
</div>
<style type="text/css">
div
{
    display:none;
 
}
a {
    color: #33739E;
    text-decoration: none;
    display: block;
    margin: 10px 0;
}
a:hover {
    text-decoration: none;
}
#loadMore {
    padding: 10px;
    text-align: center;
    background:linear-gradient(45deg, #7d7194, #464c71);
    color: #fff;
    border-width: 0 1px 1px 0;
    border-style: solid;
    border-color: #fff;
    box-shadow: 0 1px 1px #ccc;
    transition: all 600ms ease-in-out;
    -webkit-transition: all 600ms ease-in-out;
    -moz-transition: all 600ms ease-in-out;
    -o-transition: all 600ms ease-in-out;
}
#loadMore:hover {
    background-color: 	#DCDCDC;
    color: #33739E;
}
</style>
</div>
 <a href="#" id="loadMore">Load More</a>
<script type="text/javascript">


$(function () {
    $("div").slice(0, 80).show();
    $("#loadMore").on('click', function (e) {
        e.preventDefault();
        $("div:hidden").slice(0, 72).slideDown();
        if ($("div:hidden").length == 0) {
            $("#load").fadeOut('slow');
        }
        $('html,body').animate({
            scrollTop: $(this).offset().top
        }, 2000);
    });
});



	
</script>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block body %}
<div class="container" style="margin:130px; ">
<center>
    <div class="col-md-5">


        <!-- Material form contact -->
        <div class="card">

            <h5 class="card-header info-color white-text text-center py-4">
                <strong>{{title}}</strong>
            </h5>

            <!--Card content-->
            <div class="card-body px-lg-5 pt-0">

                <!-- Form -->
                <form class="text-center" method="POST" style="color: #757575;">
                    {% csrf_token %}
                    <div class="md-form mt-3">
                        {{ form.as_p }}
                    </div>

                    <!-- Login -->
                    <p>Already a member?
                        <a href="{% url 'movies:login' %}">Login</a>
                    </p>


                    <!-- Send button -->
                    <button class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4 waves-effect"
                        type="submit">Register</button>

                </form>
                <!-- Form -->

            </div>

        </div>
        <!-- Material form contact -->
    </div>


</center>
</div>
{% endblock body %}

templates/search.html
{% extends "base.html" %}

{% block body %}
<h2 style="margin-top:40px;" class="text-center">No Search Found...</h2>
{% endblock body %}